apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    gcb-build-id: 96fae361-3afa-47c9-89a8-8febc968ddf7
    gcb-trigger-id: 006a2458-7839-4676-a9b3-821a80ca31f9
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4","gcb-build-id":"96fae361-3afa-47c9-89a8-8febc968ddf7","gcb-trigger-id":"006a2458-7839-4676-a9b3-821a80ca31f9"},"creationTimestamp":"2020-03-17T14:49:14Z","generation":8,"labels":{"app":"ylz-xyz-device-svc","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"ylz-xyz-device-svc","app.kubernetes.io/version":"e528d9f9d324e22e3b0519de7af4060201162c66"},"name":"ylz-xyz-device-svc","namespace":"default","resourceVersion":"291117","selfLink":"/apis/apps/v1/namespaces/default/deployments/ylz-xyz-device-svc","uid":"78a04eca-685e-11ea-b055-42010a9c00b1"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"ylz-xyz-device-svc"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"gcb-build-id":"96fae361-3afa-47c9-89a8-8febc968ddf7","gcb-trigger-id":"006a2458-7839-4676-a9b3-821a80ca31f9"},"creationTimestamp":null,"labels":{"app":"ylz-xyz-device-svc","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"ylz-xyz-device-svc","app.kubernetes.io/version":"e528d9f9d324e22e3b0519de7af4060201162c66"}},"spec":{"containers":[{"env":[{"name":"API_PREFIX","valueFrom":{"configMapKeyRef":{"key":"API_PREFIX","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"NODE_ENV","valueFrom":{"configMapKeyRef":{"key":"NODE_ENV","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"PORT","valueFrom":{"configMapKeyRef":{"key":"PORT","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_TYPE","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_TYPE","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_PROJECT_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PROJECT_ID","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_PRIVATE_KEY_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PRIVATE_KEY_ID","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_PRIVATE_KEY","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PRIVATE_KEY","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_CLIENT_EMAIL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_EMAIL","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_CLIENT_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_ID","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_AUTH_URI","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_AUTH_URI","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_TOKEN_URI","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_TOKEN_URI","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_AUTH_PROVIDER_X509_CERT_URL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_AUTH_PROVIDER_X509_CERT_URL","name":"ylz-xyz-device-svc-config-ncgj"}}},{"name":"FIRESTORE_CLIENT_X509_CERT_URL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_X509_CERT_URL","name":"ylz-xyz-device-svc-config-ncgj"}}}],"image":"gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-device-svc@sha256:3a82053b67f74d895f58f6088b475b94457428eca902a49ca2f8b0783221a983","imagePullPolicy":"IfNotPresent","name":"ylz-xyz-device-svc-1","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2020-03-17T14:49:14Z","lastUpdateTime":"2020-03-17T15:36:16Z","message":"ReplicaSet \"ylz-xyz-device-svc-64d9b94c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2020-03-17T15:36:26Z","lastUpdateTime":"2020-03-17T15:36:26Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":8,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: "2020-03-17T14:49:14Z"
  generation: 11
  labels:
    app: ylz-xyz-device-svc
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: ylz-xyz-device-svc
    app.kubernetes.io/version: e528d9f9d324e22e3b0519de7af4060201162c66
  name: ylz-xyz-device-svc
  namespace: default
  resourceVersion: "293375"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ylz-xyz-device-svc
  uid: 78a04eca-685e-11ea-b055-42010a9c00b1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ylz-xyz-device-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gcb-build-id: 96fae361-3afa-47c9-89a8-8febc968ddf7
        gcb-trigger-id: 006a2458-7839-4676-a9b3-821a80ca31f9
      creationTimestamp: null
      labels:
        app: ylz-xyz-device-svc
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: ylz-xyz-device-svc
        app.kubernetes.io/version: e528d9f9d324e22e3b0519de7af4060201162c66
    spec:
      containers:
      - env:
        - name: API_PREFIX
          valueFrom:
            configMapKeyRef:
              key: API_PREFIX
              name: ylz-xyz-device-svc-config-ncgj
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: ylz-xyz-device-svc-config-ncgj
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_TYPE
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TYPE
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PROJECT_ID
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_PRIVATE_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY_ID
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_CLIENT_EMAIL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_EMAIL
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_ID
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_URI
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_TOKEN_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TOKEN_URI
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_CLIENT_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_X509_CERT_URL
              name: ylz-xyz-device-svc-config-ncgj
        image: gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-device-svc@sha256:3a82053b67f74d895f58f6088b475b94457428eca902a49ca2f8b0783221a983
        imagePullPolicy: IfNotPresent
        name: ylz-xyz-device-svc-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-17T14:49:14Z"
    lastUpdateTime: "2020-03-17T15:39:46Z"
    message: ReplicaSet "ylz-xyz-device-svc-d4df576bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-17T15:39:58Z"
    lastUpdateTime: "2020-03-17T15:39:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
