apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    gcb-build-id: bf9699ab-e1db-43cf-971f-d2e672c87f49
    gcb-trigger-id: ade556ad-6543-4d71-997d-8292c2ccd085
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"gcb-build-id":"bf9699ab-e1db-43cf-971f-d2e672c87f49","gcb-trigger-id":"ade556ad-6543-4d71-997d-8292c2ccd085"},"labels":{"app":"ylz-xyz-iam-svc","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"ylz-xyz-iam-svc","app.kubernetes.io/version":"ca4a65e0e29ca53756aedc0f72ce728476cd2369"},"name":"ylz-xyz-iam-svc","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ylz-xyz-iam-svc"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"gcb-build-id":"bf9699ab-e1db-43cf-971f-d2e672c87f49","gcb-trigger-id":"ade556ad-6543-4d71-997d-8292c2ccd085"},"labels":{"app":"ylz-xyz-iam-svc","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"ylz-xyz-iam-svc","app.kubernetes.io/version":"ca4a65e0e29ca53756aedc0f72ce728476cd2369"}},"spec":{"containers":[{"env":[{"name":"API_PREFIX","valueFrom":{"configMapKeyRef":{"key":"API_PREFIX","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"NODE_ENV","valueFrom":{"configMapKeyRef":{"key":"NODE_ENV","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"PORT","valueFrom":{"configMapKeyRef":{"key":"PORT","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_TYPE","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_TYPE","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_PROJECT_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PROJECT_ID","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_PRIVATE_KEY_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PRIVATE_KEY_ID","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_PRIVATE_KEY","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_PRIVATE_KEY","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_CLIENT_EMAIL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_EMAIL","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_CLIENT_ID","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_ID","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_AUTH_URI","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_AUTH_URI","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_TOKEN_URI","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_TOKEN_URI","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_AUTH_PROVIDER_X509_CERT_URL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_AUTH_PROVIDER_X509_CERT_URL","name":"ylz-xyz-iam-svc-config-e8aq"}}},{"name":"FIRESTORE_CLIENT_X509_CERT_URL","valueFrom":{"configMapKeyRef":{"key":"FIRESTORE_CLIENT_X509_CERT_URL","name":"ylz-xyz-iam-svc-config-e8aq"}}}],"image":"gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-iam-svc@sha256:acca6613a8182c106300f006c98f86ee7d94b48313a953ebdda215f4fc162f33","imagePullPolicy":"IfNotPresent","name":"ylz-xyz-iam-svc-1"}]}}}}
  creationTimestamp: "2020-03-17T03:44:48Z"
  generation: 4
  labels:
    app: ylz-xyz-iam-svc
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: ylz-xyz-iam-svc
    app.kubernetes.io/version: ca4a65e0e29ca53756aedc0f72ce728476cd2369
  name: ylz-xyz-iam-svc
  namespace: default
  resourceVersion: "202329"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ylz-xyz-iam-svc
  uid: a6bec6f1-6801-11ea-b055-42010a9c00b1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ylz-xyz-iam-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gcb-build-id: bf9699ab-e1db-43cf-971f-d2e672c87f49
        gcb-trigger-id: ade556ad-6543-4d71-997d-8292c2ccd085
      creationTimestamp: null
      labels:
        app: ylz-xyz-iam-svc
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: ylz-xyz-iam-svc
        app.kubernetes.io/version: ca4a65e0e29ca53756aedc0f72ce728476cd2369
    spec:
      containers:
      - env:
        - name: API_PREFIX
          valueFrom:
            configMapKeyRef:
              key: API_PREFIX
              name: ylz-xyz-iam-svc-config-e8aq
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: ylz-xyz-iam-svc-config-e8aq
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_TYPE
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TYPE
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PROJECT_ID
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_PRIVATE_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY_ID
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_CLIENT_EMAIL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_EMAIL
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_ID
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_URI
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_TOKEN_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TOKEN_URI
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
              name: ylz-xyz-iam-svc-config-e8aq
        - name: FIRESTORE_CLIENT_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_X509_CERT_URL
              name: ylz-xyz-iam-svc-config-e8aq
        image: gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-iam-svc@sha256:acca6613a8182c106300f006c98f86ee7d94b48313a953ebdda215f4fc162f33
        imagePullPolicy: IfNotPresent
        name: ylz-xyz-iam-svc-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-03-17T03:44:49Z"
    lastUpdateTime: "2020-03-17T09:53:44Z"
    message: ReplicaSet "ylz-xyz-iam-svc-57b8fd84b6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-17T09:53:58Z"
    lastUpdateTime: "2020-03-17T09:53:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
