apiVersion: v1
kind: Service
metadata:
  labels:
    app: ylz-xyz-iam-svc
  name: ylz-xyz-iam-svc-service
  namespace: default
spec:
  clusterIP: 10.0.25.210
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32631
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: ylz-xyz-iam-svc
  sessionAffinity: None
  type: LoadBalancer
